### ISSUE TITLE
Unable to prepare setup for platform iotawatt.sensor: Platform not found (cannot import name 'VOLT' from 'homeassistant.const' 

### ISSUE THREAD

**Issue by djhampson** [gtdiehl/iotawatt_ha#8]
```
Logger: homeassistant.setup
Source: setup.py:311
First occurred: August 3, 2021, 10:43:34 AM (2 occurrences)
Last logged: 12:19:05 PM

Unable to prepare setup for platform iotawatt.sensor: Platform not found (cannot import name 'VOLT' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).
```

I'm getting the following error when loading the iotawatt integration. This has started occurring since the core-2021.8 update.

**Comment by gtdiehl** [comment]
Yeah it appears HA 2021.8 renamed the ```VOLT``` constant to ```ELECTRIC_POTENTIAL_VOLT```

The issue is how to make the IoTaWatt integration work with <2021.8 and >=2021.8 versions?
Maybe use my own constants?

![Screen Shot 2021-08-03 at 7 48 40 PM](https://user-images.githubusercontent.com/34967045/128114052-a6214aa2-3841-4ca6-8e8e-93bec5621101.png)


![Screen Shot 2021-08-03 at 7 48 16 PM](https://user-images.githubusercontent.com/34967045/128114023-1e2ecb2f-5c07-4469-91d7-ed0e6abcc98e.png)

**Comment by gtdiehl** [comment]
@djhampson Can you update the Integration through HACS? Two changes have been made, so it should work with HA 2021.8 
 and previous HA versions now.

**Comment by djhampson** [comment]
Thanks you @gtdiehl - working again. appreciate it!
